In [1]:
import numpy as np

### 예제 1

In [37]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","joe"])
data=np.random.randint(low=30,high=100,size=(7,4))  # random 에서 int형 으로 출력
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'joe']
[[96 55 63 74]
 [85 39 83 58]
 [91 76 98 69]
 [90 37 38 88]
 [46 88 37 68]
 [41 32 76 51]
 [50 83 71 92]]


1) 이름이 Bob인 사람들만 찾기

In [6]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [8]:
names[names == "Bob"]

array(['Bob', 'Bob'], dtype='<U4')

In [39]:
data[names=="Bob"]    # data[[0,3]]와 같음, 원하는 데이터를 의미하는 조건을 찾아 입력

array([[96, 55, 63, 74],
       [90, 37, 38, 88]])

In [40]:
data[names=="Bob", :2]

array([[96, 55],
       [90, 37]])

In [41]:
data[names=="Bob"][0]   # 첫번째 Bob의 성적 가져오기

array([96, 55, 63, 74])

2) 이름이 Bob과 Will인 사람 찾기

In [42]:
data[(names=="Bob") | (names=="Will"), :2]

array([[96, 55],
       [91, 76],
       [90, 37],
       [46, 88]])

((((심화))))<br>
90점 초과해야지 그 과목 통과, 아니면 통과 못한다.<br>
그 학기 이수를 위해서는 통과한 과목이 1과목 이상이여야 한다.<br>
누가 이번 학기를 이수할 수 있을까?

In [38]:
# 성적 백업
z=data
z

array([[96, 55, 63, 74],
       [85, 39, 83, 58],
       [91, 76, 98, 69],
       [90, 37, 38, 88],
       [46, 88, 37, 68],
       [41, 32, 76, 51],
       [50, 83, 71, 92]])

In [43]:
data[data<90]=0   # 90 미만의 점수를 0으로 바꿈
data

array([[96,  0,  0,  0],
       [ 0,  0,  0,  0],
       [91,  0, 98,  0],
       [90,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0, 92]])

In [44]:
# data[data>=90]=1
# data[data<90]=0    # 주의))이와 같은 순서면 모든 데이터가 0이 된다

data[data>=90]=1 
data

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [45]:
np.where(data>0)       # np.where(조건) => 조건의 위치 정보를 가져옴

(array([0, 2, 2, 3, 6], dtype=int64), array([0, 0, 2, 0, 3], dtype=int64))

In [46]:
#결과가 튜플 형식이므로, 학생을 나타내는 첫번째 요소만 가져온다
np.where(data>0)[0]

array([0, 2, 2, 3, 6], dtype=int64)

In [47]:
# np.unique() => 중복된 값을 지우고 하나의 값만 정리한다.
np.unique(np.where(data>0)[0])

array([0, 2, 3, 6], dtype=int64)

In [48]:
names[np.unique(np.where(data>0)[0])]

array(['Bob', 'Will', 'Bob', 'joe'], dtype='<U4')