# NumPy

In [32]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

기존 Python의 array는 메모리상에 따로따로 저장된다.<br>
ndarray는 메모리에 순서대로 저장되기에 접근이 더 용이하고 빠르다.<br>
np.array(...)

In [7]:
# 파이썬의 기본 리스트   // 데이터가 중구난방하게 저장되어있다.
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

a=[16,17,18,19,20] a의 모든 원소에 일괄적으로 +15

In [8]:
# 파이썬의 기본 리스트 문법
a=[16,17,18,19,20]
b=[]
for i in range(0,len(a)):
    b.append(a[i]+15)
print(b)

[31, 32, 33, 34, 35]


In [17]:
# ndarray 사용
a=[16,17,18,19,20]
import numpy as np
a=np.array(a)
a      # 이와 같이 출력하여 기본리스트은지 ndarry인지 알 수 있다
print(a+15)

[31 32 33 34 35]


In [21]:
# 파이썬의 기본 리스트 문법
a=[1,2,3,4,5,6,7,8,9,10]
b=[11,12,13,14,15,16,17,18,19,20]
c=[]
for i in range(0,len(a)):
    c.append(a[i]+b[i])
print(c)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


In [23]:
# 기본 리스트는 연결 시켜버린다.
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [24]:
# ndarray 사용
a_arr=np.array(a)
b_arr=np.array(b)

c=a_arr + b_arr
print(c)

[12 14 16 18 20 22 24 26 28 30]


참고) 벡터 스칼라 연산

In [28]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("\n")
print(arr*arr)

[[1 2 3]
 [4 5 6]]


[[ 1  4  9]
 [16 25 36]]


# 기본 정보 확인: 차원, 모습, 타입 등

In [36]:
arr1=[1,2.0,3,"4",5,6]
arr1=np.array(arr1)
print(arr1.ndim)  # 몇차원인지
print(arr1.shape)  # 몇행인지(,몇 열인지)
print(arr1.dtype)  # 데이터 타입

1
(6,)
<U32


# 개별 원소 접근 방식<br>
    기본적인 파이썬의 리스트와 동일 --> 정수 인덱스 활용

In [37]:
arr1

array(['1', '2.0', '3', '4', '5', '6'], dtype='<U32')

In [38]:
arr1[1]

'2.0'

In [40]:
arr1[1:4]

array(['2.0', '3', '4'], dtype='<U32')

In [42]:
arr2=np.arange(10)
print(arr2[2:9:2])

[2 4 6 8]


### 예제 2

In [43]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [44]:
np.arange(0,60,10)

array([ 0, 10, 20, 30, 40, 50])

In [49]:
np.arange(0,60,10)[:,np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [51]:
a= np.arange(0,60,10)[:,np.newaxis]+np.arange(0,6,1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [52]:
a[0][3:5]  # a[0, 3:5] 와 같음

array([3, 4])

In [66]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [69]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [68]:
a[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [70]:
# Boolean indexing
arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
